dist: bionic

language: python

python:
  - "3.7"

cache:
  - pip

env:
  global:
    #- secure: "av7eQ6L/TybtjAnhrtGVR9ja6dZMLLSHK8fljuzl4MdYv4/OI0ftTXm2o6JZNQ6jfwoWu3kRQCcrWYXLEPvWB4qaAcjyd9Wohm/1U1zcgOK6Gb3zIohKkDW0Vc5ciZp8joDrVMKGNgh49IPElRUYUIZAC/uWKYAcKZQhzo0UM5v1zIOBrL/WoRZ2KaOwva+vPbIlUOSwe7k0mg4aJghD7YqJwmb81H/TW2wP2xvksnnF5fKW8ODGCpRK0flgftxVx1tZyIVgGfe4ach2PLKaZa0F24ifyRBdPNAeCXGsC/9EcPePlJXuVVb91jmdUhq9Zcc1NZOqOGhvGUKKkvcizG0JgCgu9/DgahxKLiu2h20a+mvKGATZm2Q8FF4YjHpNMyeF3eUyTwrjIdS7+/7XD6igg/zD/i9jaXPwQEFvgYWCuAsqcAXQHPAUM41w3ifqmDlJhwmPIXsdf+OlPCvlhEiZBZWXmZjK96EMFRtdsdbt2RcC2jHXLeu8eCrAkoebyi/jXO7e+w9K+40U1eszH3diBSz7uCJvsyL0m0mZ1cq88nCjDl/yDeBiuCp+1MzlK0axeLj/YxUvgAEQnhGUEXm/Iyc6Z0JJaBS5SxCKMTEL9R7ApPtoqGdW88OWFVanEvNTJK+MhzUcMJuOqaSNY2mDkYQW5/njjNrWjFCFk64="
    - GIT_NAME: "Spirillen"
    - GIT_EMAIL: 44526987+spirillen@users.noreply.github.com
    #- GIT_NAME: "TravisCI"
    #- GIT_EMAIL: "travis@travis-ci.org"
    - TRAVIS_REPO_SLUG: ${TRAVIS_REPO_SLUG}
    - GIT_BRANCH: master
    - TZ: UTC
    - PYFUNCEBLE_CONFIG_DIR: ${TRAVIS_BUILD_DIR}/dev-tools/
    - PYFUNCEBLE_AUTO_CONFIGURATION: PyFunceble

addons:
  apt:
    packages:
    - dos2unix
    - msttcorefonts
    #- pdns-recursor
    update: true

install:
  - export PATH="${HOME}/miniconda/bin:${PATH}"
  - if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh; fi
  - bash miniconda.sh -b -p ${HOME}/miniconda
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda create -q -n test-environment python="${PYTHON_VERSION}"
  - source activate test-environment
  - python --version --version
  - pip --version
  - conda --version
  #- pip3 install --upgrade pip
  - pip install pyfunceble-dev ultimate-hosts-blacklist-whitelist

git:
  depth: 5

matrix:
  fast_finish: true

sudo: required

script:
  - sudo bash "${TRAVIS_BUILD_DIR}/dev-tools/setup_recursor.sh"
  #- sudo systemctl restart pdns-recursor.service && sudo systemctl status pdns-recursor.service
  - bash dev-tools/domain_combine.sh 
